<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.css">
    <!-- Compiled and minified JavaScript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.2.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.js"></script>
    <style>
        body {
	    text-align: center;
	    display: flex;
            align-items: center;
            justify-content: center;
	    background-color: gainsboro;
        }
       .jooj {
	    border-radius: 25px;
	    border: 5px;
	    background-color: white;
	    display: block;
            align-items: center;
            justify-content: center;
	    padding: 10px 0px 10px 0px;
            width: 500px;
    	    margin-left: 250px;
	}
</style>
</head>